security:
    basic:
        enabled: false

management:
    security:
        enabled: false

logging: # <----New sections below
    pattern:
        console: "%-5level %logger{36} : %msg%n"
    level:
        root: WARN
        io:
            pivotal: DEBUG

greeting:
    displayFortune: false

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
